// Objective-C API for talking to github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/activitylogger/mem Go package.
//   gobind -lang=objc github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/activitylogger/mem
//
// File is generated by gobind. Do not edit.

#ifndef __Mem_H__
#define __Mem_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Api.objc.h"

@class MemActivityLogger;

/**
 * ActivityLogger is a simple in-memory api.ActivityLogger implementation.
New activities are appended to the array in the order that they are received.
 */
@interface MemActivityLogger : NSObject <goSeqRefInterface, ApiActivityLogger> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewActivityLogger returns a new ActivityLogger.
 */
- (nullable instancetype)init;
/**
 * AtIndex returns the activity stored at the given index.
Passing in 0 for the index will return the first activity in the underlying array. If this activity logger is only
being used in one thread at a time, then that activity will be first activity that this activity logger has logged,
and using higher indices will return more recent activities.
If the index passed in is out of bounds, then nil is returned.
 */
- (ApiActivity* _Nullable)atIndex:(long)index;
/**
 * Length returns the number of activities that this activity logger has logged.
 */
- (long)length;
/**
 * Log logs a single activity.
The activity is appended to the end of an internal array of activities.
 */
- (BOOL)log:(ApiActivity* _Nullable)activity error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * NewActivityLogger returns a new ActivityLogger.
 */
FOUNDATION_EXPORT MemActivityLogger* _Nullable MemNewActivityLogger(void);

#endif
