
// Objective-C API for talking to the following Go packages
//
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/activitylogger/mem
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/api
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/api/vcparse
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/credential
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/did
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/ld
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/localkms
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/openid4ci
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/openid4vp
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/walleterror
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Walletsdk_FRAMEWORK_H__
#define __Walletsdk_FRAMEWORK_H__

#include "Mem.objc.h"
#include "Api.objc.h"
#include "Vcparse.objc.h"
#include "Credential.objc.h"
#include "Did.objc.h"
#include "Ld.objc.h"
#include "Localkms.objc.h"
#include "Openid4ci.objc.h"
#include "Openid4vp.objc.h"
#include "Walleterror.objc.h"
#include "Universe.objc.h"

#endif
