// Objective-C API for talking to github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/openid4vp Go package.
//   gobind -lang=objc github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/openid4vp
//
// File is generated by gobind. Do not edit.

#ifndef __Openid4vp_H__
#define __Openid4vp_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Api.objc.h"
#include "Walleterror.objc.h"

@class Openid4vpClientConfig;
@class Openid4vpInteraction;

/**
 * ClientConfig contains various parameters for an OpenID4VP Interaction.
ActivityLogger is optional, but if provided then activities will be logged there.
If not provided, then no activities will be logged.
 */
@interface Openid4vpClientConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewClientConfig creates the client config object.
ActivityLogger is optional, but if provided then activities will be logged there.
If not provided, then no activities will be logged.
 */
- (nullable instancetype)init:(id<ApiKeyReader> _Nullable)keyHandleReader crypto:(id<ApiCrypto> _Nullable)crypto didResolver:(id<ApiDIDResolver> _Nullable)didResolver ldDocumentLoader:(id<ApiLDDocumentLoader> _Nullable)ldDocumentLoader activityLogger:(id<ApiActivityLogger> _Nullable)activityLogger;
@property (nonatomic) id<ApiKeyReader> _Nullable keyHandleReader;
@property (nonatomic) id<ApiCrypto> _Nullable crypto;
@property (nonatomic) id<ApiDIDResolver> _Nullable didRes;
@property (nonatomic) id<ApiLDDocumentLoader> _Nullable documentLoader;
@property (nonatomic) id<ApiActivityLogger> _Nullable activityLogger;
@end

/**
 * Interaction represents a single OpenID4VP interaction between a wallet and a verifier. The methods defined on this
object are used to help guide the calling code through the OpenID4VP flow.
 */
@interface Openid4vpInteraction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewInteraction creates a new OpenID4VP Interaction.
The methods defined on this object are used to help guide the calling code through the OpenID4CI flow.
If activityLogger is nil, then no activity logging will take place.
 */
- (nullable instancetype)init:(NSString* _Nullable)authorizationRequest config:(Openid4vpClientConfig* _Nullable)config;
/**
 * GetQuery creates query based on authorization request data.
 */
- (NSData* _Nullable)getQuery:(NSError* _Nullable* _Nullable)error;
/**
 * PresentCredential presents credentials to redirect uri from request object.
 */
- (BOOL)presentCredential:(NSData* _Nullable)presentation vm:(ApiVerificationMethod* _Nullable)vm error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Constants' names and reasons are obvious so they do not require additional comments.
nolint:golint,nolintlint
 */
FOUNDATION_EXPORT const int64_t Openid4vpCredentialParseFailedCode;
/**
 * Constants' names and reasons are obvious so they do not require additional comments.
nolint:golint,nolintlint
 */
FOUNDATION_EXPORT NSString* _Nonnull const Openid4vpCredentialParseFailedError;

/**
 * NewClientConfig creates the client config object.
ActivityLogger is optional, but if provided then activities will be logged there.
If not provided, then no activities will be logged.
 */
FOUNDATION_EXPORT Openid4vpClientConfig* _Nullable Openid4vpNewClientConfig(id<ApiKeyReader> _Nullable keyHandleReader, id<ApiCrypto> _Nullable crypto, id<ApiDIDResolver> _Nullable didResolver, id<ApiLDDocumentLoader> _Nullable ldDocumentLoader, id<ApiActivityLogger> _Nullable activityLogger);

/**
 * NewInteraction creates a new OpenID4VP Interaction.
The methods defined on this object are used to help guide the calling code through the OpenID4CI flow.
If activityLogger is nil, then no activity logging will take place.
 */
FOUNDATION_EXPORT Openid4vpInteraction* _Nullable Openid4vpNewInteraction(NSString* _Nullable authorizationRequest, Openid4vpClientConfig* _Nullable config);

#endif
