// Objective-C API for talking to github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/api/vcparse Go package.
//   gobind -lang=objc github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/api/vcparse
//
// File is generated by gobind. Do not edit.

#ifndef __Vcparse_H__
#define __Vcparse_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Api.objc.h"

@class VcparseOpts;

/**
 * Opts represents various options for the Parse function.
 */
@interface VcparseOpts : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewOpts returns a new Opts object for use with the Parse function.
 */
- (nullable instancetype)init:(BOOL)disableProofCheck documentLoader:(id<ApiLDDocumentLoader> _Nullable)documentLoader;
@property (nonatomic) BOOL disableProofCheck;
@property (nonatomic) id<ApiLDDocumentLoader> _Nullable documentLoader;
@end

/**
 * NewOpts returns a new Opts object for use with the Parse function.
 */
FOUNDATION_EXPORT VcparseOpts* _Nullable VcparseNewOpts(BOOL disableProofCheck, id<ApiLDDocumentLoader> _Nullable documentLoader);

/**
 * Parse parses the given serialized VC into a VC object.
 */
FOUNDATION_EXPORT ApiVerifiableCredential* _Nullable VcparseParse(NSString* _Nullable vc, VcparseOpts* _Nullable opts, NSError* _Nullable* _Nullable error);

#endif
