// Objective-C API for talking to github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/walleterror Go package.
//   gobind -lang=objc github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/walleterror
//
// File is generated by gobind. Do not edit.

#ifndef __Walleterror_H__
#define __Walleterror_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class WalleterrorError;

/**
 * Error represents error returned by go mobile api.
 */
@interface WalleterrorError : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull code;
@property (nonatomic) NSString* _Nonnull category;
@property (nonatomic) NSString* _Nonnull details;
@end

/**
 * Parse used to parse exception message on mobile side.
 */
FOUNDATION_EXPORT WalleterrorError* _Nullable WalleterrorParse(NSString* _Nullable message);

/**
 * ToMobileError translates go api errors to go mobile errors.
 */
FOUNDATION_EXPORT BOOL WalleterrorToMobileError(NSError* _Nullable err, NSError* _Nullable* _Nullable error);

#endif
